version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: services/vector-db/Dockerfile
    environment:
      MILVUS_HOST: localhost
      MILVUS_PORT: '19530'
    ports:
      - "9013:8080"
