AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Milvus and vector search Lambdas.

Parameters:
  MilvusHost:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/host
  MilvusPort:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/port
  MilvusCollection:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/collection
  ElasticsearchUrl:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/elasticsearch/url
  ElasticsearchIndexPrefix:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/elasticsearch/index

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.13
    Timeout: 60
    MemorySize: 512

Resources:
  MilvusInsertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-insert-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  MilvusDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-delete-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  MilvusUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-update-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  MilvusCreateCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-create-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  MilvusDropCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-drop-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  VectorSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./vector-search-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  HybridSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./hybrid-search-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  EsInsertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./es-insert-lambda/
      Environment:
        Variables:
          ELASTICSEARCH_URL: !Ref ElasticsearchUrl
          ELASTICSEARCH_INDEX_PREFIX: !Ref ElasticsearchIndexPrefix

  EsDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./es-delete-lambda/
      Environment:
        Variables:
          ELASTICSEARCH_URL: !Ref ElasticsearchUrl
          ELASTICSEARCH_INDEX_PREFIX: !Ref ElasticsearchIndexPrefix

  EsUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./es-update-lambda/
      Environment:
        Variables:
          ELASTICSEARCH_URL: !Ref ElasticsearchUrl
          ELASTICSEARCH_INDEX_PREFIX: !Ref ElasticsearchIndexPrefix

  EsCreateIndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./es-create-lambda/
      Environment:
        Variables:
          ELASTICSEARCH_URL: !Ref ElasticsearchUrl
          ELASTICSEARCH_INDEX_PREFIX: !Ref ElasticsearchIndexPrefix

  EsDropIndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./es-drop-lambda/
      Environment:
        Variables:
          ELASTICSEARCH_URL: !Ref ElasticsearchUrl
          ELASTICSEARCH_INDEX_PREFIX: !Ref ElasticsearchIndexPrefix

  EsSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./es-search-lambda/
      Environment:
        Variables:
          ELASTICSEARCH_URL: !Ref ElasticsearchUrl
          ELASTICSEARCH_INDEX_PREFIX: !Ref ElasticsearchIndexPrefix

  EsHybridSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./es-hybrid-search-lambda/
      Environment:
        Variables:
          ELASTICSEARCH_URL: !Ref ElasticsearchUrl
          ELASTICSEARCH_INDEX_PREFIX: !Ref ElasticsearchIndexPrefix

Outputs:
  MilvusInsertFunctionArn:
    Description: ARN of the Milvus insert Lambda
    Value: !GetAtt MilvusInsertFunction.Arn
  MilvusDeleteFunctionArn:
    Description: ARN of the Milvus delete Lambda
    Value: !GetAtt MilvusDeleteFunction.Arn
  MilvusUpdateFunctionArn:
    Description: ARN of the Milvus update Lambda
    Value: !GetAtt MilvusUpdateFunction.Arn
  MilvusCreateCollectionFunctionArn:
    Description: ARN of the Milvus create collection Lambda
    Value: !GetAtt MilvusCreateCollectionFunction.Arn
  MilvusDropCollectionFunctionArn:
    Description: ARN of the Milvus drop collection Lambda
    Value: !GetAtt MilvusDropCollectionFunction.Arn
  VectorSearchFunctionArn:
    Description: ARN of the vector search Lambda
    Value: !GetAtt VectorSearchFunction.Arn
  HybridSearchFunctionArn:
    Description: ARN of the hybrid search Lambda
    Value: !GetAtt HybridSearchFunction.Arn
  EsInsertFunctionArn:
    Description: ARN of the Elasticsearch insert Lambda
    Value: !GetAtt EsInsertFunction.Arn
  EsDeleteFunctionArn:
    Description: ARN of the Elasticsearch delete Lambda
    Value: !GetAtt EsDeleteFunction.Arn
  EsUpdateFunctionArn:
    Description: ARN of the Elasticsearch update Lambda
    Value: !GetAtt EsUpdateFunction.Arn
  EsCreateIndexFunctionArn:
    Description: ARN of the Elasticsearch create index Lambda
    Value: !GetAtt EsCreateIndexFunction.Arn
  EsDropIndexFunctionArn:
    Description: ARN of the Elasticsearch drop index Lambda
    Value: !GetAtt EsDropIndexFunction.Arn
  EsSearchFunctionArn:
    Description: ARN of the Elasticsearch search Lambda
    Value: !GetAtt EsSearchFunction.Arn
  EsHybridSearchFunctionArn:
    Description: ARN of the Elasticsearch hybrid search Lambda
    Value: !GetAtt EsHybridSearchFunction.Arn
