AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Workflow to summarize APS ZIP archives.

Globals:
  Function:
    Timeout: 3
    Runtime: python3.13

Parameters:
  AWSAccountName:
    Type: String
    Description: AWS Account Name

  ZipExtractLambdaArn:
    Type: String
    Description: ARN of the Lambda used to extract ZIP archives

  ZipfileCreationLambdaArn:
    Type: String
    Description: ARN of the Lambda that packages the summarized PDFs

  FileProcessingStepFunctionArn:
    Type: String
    Description: ARN of the per-file summarization state machine

  StepFunctionRoleArn:
    Type: String
    Description: IAM role ARN for the APS summarization workflow

  LambdaIAMRoleARN:
    Type: String
    Description: IAM Role ARN for Lambda functions used in this workflow

Resources:
  RunPromptsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWSAccountName}-${AWS::StackName}-run-prompts'
      Handler: run_prompts_lambda.lambda_handler
      Runtime: python3.13
      CodeUri: ./src/
      Role: !Ref LambdaIAMRoleARN
      Environment:
        Variables:
          SUMMARIZATION_STATE_MACHINE_ARN: !Ref FileProcessingStepFunctionArn

  ConsolidateSummaryLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWSAccountName}-${AWS::StackName}-consolidate-summary'
      Handler: consolidate_summary_lambda.lambda_handler
      Runtime: python3.13
      CodeUri: ./src/
      Role: !Ref LambdaIAMRoleARN

  FileAssemblyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWSAccountName}-${AWS::StackName}-file-assembly'
      Handler: file_assembly_lambda.lambda_handler
      Runtime: python3.13
      CodeUri: ./src/
      Role: !Ref LambdaIAMRoleARN

  ApsSummarizationStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub '${AWSAccountName}-${AWS::StackName}-aps-summary'
      Role: !Ref StepFunctionRoleArn
      Definition:
        Comment: Extract uploaded ZIPs, summarize PDFs and re-package results
        StartAt: ExtractZip
        States:
          ExtractZip:
            Type: Task
            Resource: !Ref ZipExtractLambdaArn
            ResultPath: $
            Next: CheckZipExtractStatus
          CheckZipExtractStatus:
            Type: Choice
            Choices:
              - Not:
                  Variable: $.statusCode
                  NumericEquals: 200
                Next: AssembleZip
            Default: ProcessAllPdfs
          ProcessAllPdfs:
            Type: Map
            ItemsPath: $.pdfFiles
            ResultPath: $.files
            MaxConcurrency: 5
            Iterator:
              StartAt: RunPrompts
              States:
                RunPrompts:
                  Type: Task
                  Resource: !GetAtt RunPromptsLambdaFunction.Arn
                  ResultPath: $.execution
                  Next: ConsolidateSummary
                ConsolidateSummary:
                  Type: Task
                  Resource: !GetAtt ConsolidateSummaryLambdaFunction.Arn
                  Parameters:
                    executions.$: $.execution.executionArn
                  ResultPath: $.summary
                  Next: FileAssemble
                FileAssemble:
                  Type: Task
                  Resource: !GetAtt FileAssemblyLambdaFunction.Arn
                  ResultPath: $.processedFiles
                  End: true
            Next: AssembleZip
          AssembleZip:
            Type: Task
            Resource: !Ref ZipfileCreationLambdaArn
            ResultPath: $
            End: true
      Logging:
        Level: 'OFF'
        IncludeExecutionData: false

Outputs:
  ApsSummarizationStateMachineArn:
    Description: ARN of the APS summarization workflow
    Value: !Ref ApsSummarizationStateMachine
