AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Wrapper state machine for APS summarization

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Runtime: python3.13
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON

Parameters:
  AWSAccountName:
    Type: String
  LambdaIAMRoleARN:
    Type: String
  LambdaSubnet1ID:
    Type: String
  LambdaSubnet2ID:
    Type: String
  LambdaSecurityGroupID1:
    Type: String
  LambdaSecurityGroupID2:
    Type: String
  FileAssembleFunctionArn:
    Type: String
  FileIngestionStateMachineArn:
    Type: String
  PromptEngineEndpoint:
    Type: String
  RAGSummaryFunctionArn:
    Type: String
  VectorDbProxyFunctionArn:
    Type: String
  FileProcessingEmailId:
    Type: String
  FontDir:
    Type: String
    Default: ./src
  LabelsPath:
    Type: String
    Default: ./config/summary_labels.json

Resources:
  SummarizationService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../services/summarization/template.yaml
      Parameters:
        AWSAccountName: !Ref AWSAccountName
        LambdaSubnet1ID: !Ref LambdaSubnet1ID
        LambdaSubnet2ID: !Ref LambdaSubnet2ID
        LambdaSecurityGroupID1: !Ref LambdaSecurityGroupID1
        LambdaSecurityGroupID2: !Ref LambdaSecurityGroupID2
        LambdaIAMRoleARN: !Ref LambdaIAMRoleARN
        FileAssembleFunctionArn: !Ref FileAssembleFunctionArn
        FileIngestionStateMachineArn: !Ref FileIngestionStateMachineArn
        PromptEngineEndpoint: !Ref PromptEngineEndpoint
        RAGSummaryFunctionArn: !Ref RAGSummaryFunctionArn

  ZipProcessingService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ../../services/zip-processing/template.yaml
      Parameters:
        AWSAccountName: !Ref AWSAccountName
        LambdaSubnet1ID: !Ref LambdaSubnet1ID
        LambdaSubnet2ID: !Ref LambdaSubnet2ID
        LambdaSecurityGroupID1: !Ref LambdaSecurityGroupID1
        LambdaSecurityGroupID2: !Ref LambdaSecurityGroupID2
        LambdaIAMRoleARN: !Ref LambdaIAMRoleARN
        FileProcessingStepFunctionArn: !GetAtt SummarizationService.Outputs.SummarizationWorkflowArn
        FileProcessingStepFunctionIAMRole: !Ref LambdaIAMRoleARN
        FileProcessingEmailId: !Ref FileProcessingEmailId

  APSWorkflowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWSAccountName}-${AWS::StackName}-aps-workflow'
      Handler: aps_workflow_lambda.lambda_handler
      CodeUri: ./src/
      Runtime: python3.13
      Role: !Ref LambdaIAMRoleARN
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupID1
          - !Ref LambdaSecurityGroupID2
        SubnetIds:
          - !Ref LambdaSubnet1ID
          - !Ref LambdaSubnet2ID
      Environment:
        Variables:
          FONT_DIR: !Ref FontDir
          DEFAULT_VECTOR_DB_BACKEND: milvus

  ZipSFStartPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWSAccountName}-${AWS::StackName}-zip-sf-start'
      Roles:
        - !Select [1, !Split ['/', !Ref LambdaIAMRoleARN]]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: states:StartExecution
            Resource: !GetAtt ZipProcessingService.Outputs.ZipFileProcessingStepFunctionArn

  VectorDbInvokePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWSAccountName}-${AWS::StackName}-vector-db-invoke'
      Roles:
        - !Select [1, !Split ['/', !Ref LambdaIAMRoleARN]]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource: !Ref VectorDbProxyFunctionArn

  APSStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        Comment: APS summarization wrapper
        StartAt: CreateCollection
        States:
          CreateCollection:
            Type: Task
            Resource: !Ref VectorDbProxyFunctionArn
            Parameters:
              operation: create
              collection_name: aps-summary-collection
              ephemeral: true
              expires_at.$: States.Format('{}', States.MathAdd($$.Execution.StartTime, 86400))
            Next: ProcessZip
          ProcessZip:
            Type: Task
            Resource: arn:aws:states:::states:startExecution.sync
            Parameters:
              StateMachineArn: !GetAtt ZipProcessingService.Outputs.ZipFileProcessingStepFunctionArn
              Input:
                workflow_id: aps
                font_dir: !Ref FontDir
                labels_path: !Ref LabelsPath
                collection_name: aps-summary-collection
                storage_mode: milvus
                body.$: $.body
            Next: PostProcess
          PostProcess:
            Type: Task
            Resource: !GetAtt APSWorkflowFunction.Arn
            End: true
        QueryLanguage: JSONata
      Role: !Ref LambdaIAMRoleARN
      Type: STANDARD

Outputs:
  APSStateMachineArn:
    Description: ARN of the APS summarization workflow
    Value: !Ref APSStateMachine
  ZipFileProcessingStepFunctionArn:
    Description: ARN of the zip file processing state machine
    Value: !GetAtt ZipProcessingService.Outputs.ZipFileProcessingStepFunctionArn
  SummarizationWorkflowArn:
    Description: ARN of the summarization workflow
    Value: !GetAtt SummarizationService.Outputs.SummarizationWorkflowArn
