version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: services/summarization/Dockerfile
    environment:
      FILE_ASSEMBLE_FUNCTION_ARN: arn:aws:lambda:region:acct:function:file-assemble
    ports:
      - "9011:8080"
