AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Summarization workflow invoking the file ingestion service.

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Runtime: python3.13
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON

Parameters:
  AWSAccountName:
    Type: String
    Description: AWS Account Name

  LambdaSubnet1ID:
    Type: String
    Description: Subnet ID for Lambda function

  LambdaSubnet2ID:
    Type: String
    Description: Subnet ID for Lambda function

  LambdaSecurityGroupID1:
    Type: String
    Description: Security Group ID for Lambda functions
  LambdaSecurityGroupID2:
    Type: String
    Description: Security Group ID for Lambda functions
  LambdaIAMRoleARN:
    Type: String
    Description: IAM Role ARN for Lambda functions

  FileProcessingStepFunctionIAMRole:
    Type: String
    Description: IAM role ARN for step functions

  FileIngestionStateMachineArn:
    Type: String
    Description: ARN of the file ingestion Step Function

  RagSummaryFunctionArn:
    Type: String
    Description: ARN of the RAG retrieval summary Lambda

  FileAssembleFunctionArn:
    Type: String
    Description: ARN of the file assemble Lambda

  RunPromptsConcurrency:
    Type: Number
    Default: 10
    Description: MaxConcurrency for the run_prompts map state

  PromptEngineEndpoint:
    Type: String
    Default: ""
    Description: URL of the Prompt Engine service


Resources:
  SummaryQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  FileSummaryLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${AWSAccountName}-${AWS::StackName}-file-summary-layer'
      Description: Layer for file summary Lambda
      ContentUri: ../../common/layers/file-summary-lambda-layer/
      RetentionPolicy: Delete
      CompatibleRuntimes:
        - python3.13

  FileSummaryLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWSAccountName}-${AWS::StackName}-file-summary'
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: ./file-summary-lambda/
      Role: !Ref LambdaIAMRoleARN
      MemorySize: 1024
      Timeout: 720
      EphemeralStorage:
        Size: 2068
      Layers:
        - !Ref FileSummaryLambdaLayer
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupID1
          - !Ref LambdaSecurityGroupID2
        SubnetIds:
          - !Ref LambdaSubnet1ID
          - !Ref LambdaSubnet2ID
      Environment:
        Variables:
          AWS_ACCOUNT_NAME: !Ref AWSAccountName

  SummarizeWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWSAccountName}-${AWS::StackName}-summarize-worker'
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: ./summarize-worker-lambda/
      Role: !Ref LambdaIAMRoleARN
      MemorySize: 512
      Timeout: 300
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupID1
          - !Ref LambdaSecurityGroupID2
        SubnetIds:
          - !Ref LambdaSubnet1ID
          - !Ref LambdaSubnet2ID
      Environment:
        Variables:
          RAG_SUMMARY_FUNCTION_ARN: !Ref RagSummaryFunctionArn
          PROMPT_ENGINE_ENDPOINT: !Ref PromptEngineEndpoint
      Events:
        Queue:
          Type: SQS
          Properties:
            Queue: !GetAtt SummaryQueue.Arn
            BatchSize: 1

  LoadPromptsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWSAccountName}-${AWS::StackName}-load-prompts'
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: ./load-prompts-lambda/
      Role: !Ref LambdaIAMRoleARN
      Timeout: 60
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupID1
          - !Ref LambdaSecurityGroupID2
        SubnetIds:
          - !Ref LambdaSubnet1ID
          - !Ref LambdaSubnet2ID
      Environment:
        Variables:
          PROMPT_ENGINE_ENDPOINT: !Ref PromptEngineEndpoint
          SYSTEM_WORKFLOW_ID: sys

  WorkerSQSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWSAccountName}-${AWS::StackName}-worker-sqs'
      Roles:
        - !Select [1, !Split ['/', !Ref LambdaIAMRoleARN]]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt SummaryQueue.Arn

  LoadPromptsDynamoPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWSAccountName}-${AWS::StackName}-load-prompts-dynamo'
      Roles:
        - !Select [1, !Split ['/', !Ref LambdaIAMRoleARN]]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:Query
            Resource: '*'

  WorkerSFCallbackPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWSAccountName}-${AWS::StackName}-worker-callback'
      Roles:
        - !Select [1, !Split ['/', !Ref LambdaIAMRoleARN]]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - states:SendTaskSuccess
              - states:SendTaskFailure
            Resource: !Ref SummarizationWorkflow

  FileIngestionSFInvokePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWSAccountName}-${AWS::StackName}-file-ingestion-sf-invoke'
      Roles:
        - !Select [1, !Split ['/', !Ref FileProcessingStepFunctionIAMRole]]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - states:StartExecution
            Resource: !Ref FileIngestionStateMachineArn

  SummarizationSFInvokePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWSAccountName}-${AWS::StackName}-summarization-sf-invoke'
      Roles:
        - !Select [1, !Split ['/', !Ref FileProcessingStepFunctionIAMRole]]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - states:StartExecution
            Resource: !Ref SummarizationWorkflow

  StepFunctionSQSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWSAccountName}-${AWS::StackName}-sf-sqs-send'
      Roles:
        - !Select [1, !Split ['/', !Ref FileProcessingStepFunctionIAMRole]]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt SummaryQueue.Arn

  SummarizationWorkflow:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: workflow/summarization.asl.json
      DefinitionSubstitutions:
        SummaryQueueUrl: !Ref SummaryQueue
        LoadPromptsFunctionArn: !GetAtt LoadPromptsFunction.Arn
        FileSummaryLambdaFunctionArn: !GetAtt FileSummaryLambdaFunction.Arn
        RunPromptsConcurrency: !Ref RunPromptsConcurrency
      Name: !Sub '${AWSAccountName}-${AWS::StackName}-summarization-sf'
      Type: STANDARD
      Role: !Ref FileProcessingStepFunctionIAMRole
      Logging:
        Level: 'OFF'
        IncludeExecutionData: false

  FileProcessingStepFunction:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        Comment: Orchestrate file ingestion and summarization
        StartAt: file_ingestion
        States:
          file_ingestion:
            Type: Task
            Resource: arn:aws:states:::states:startExecution.sync
            Output: '{% $states.input %}'
            Parameters:
              StateMachineArn: !Ref FileIngestionStateMachineArn
              Input: '{% $states.input %}'
            Next: summarization_workflow
          summarization_workflow:
            Type: Task
            Resource: arn:aws:states:::states:startExecution.sync
            Parameters:
              StateMachineArn: !Ref SummarizationWorkflow
              Input.$: $
            Next: file_assemble
          file_assemble:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Output: '{% $states.result.Payload %}'
            Arguments:
              FunctionName: !Ref FileAssembleFunctionArn
              Payload: '{% $states.input %}'
            Retry:
              - ErrorEquals:
                  - States.TaskFailed
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 3
                BackoffRate: 2
                JitterStrategy: FULL
            End: true
        QueryLanguage: JSONata
      Name: !Sub '${AWSAccountName}-${AWS::StackName}-file-processing-sf'
      Type: STANDARD
      Role: !Ref FileProcessingStepFunctionIAMRole
      Logging:
        Level: 'OFF'
        IncludeExecutionData: false

Outputs:
  FileProcessingStepFunctionArn:
    Description: ARN of the file processing state machine
    Value: !Ref FileProcessingStepFunction
  SummarizationWorkflowArn:
    Description: ARN of the summarization state machine
    Value: !Ref SummarizationWorkflow
  SummaryQueueUrl:
    Description: URL of the summarization queue
    Value: !Ref SummaryQueue
