version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: services/rag-ingestion-worker/Dockerfile
    environment:
      STATE_MACHINE_ARN: arn:aws:states:region:acct:stateMachine:ingest
      QUEUE_URL: https://sqs.region.amazonaws.com/123/queue
    ports:
      - "9013:8080"
