AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Queue worker for the RAG ingestion workflow.

Parameters:
  AWSAccountName:
    Type: String
  LambdaSubnet1ID:
    Type: String
  LambdaSubnet2ID:
    Type: String
  LambdaSecurityGroupID1:
    Type: String
  LambdaSecurityGroupID2:
    Type: String
  LambdaIAMRoleARN:
    Type: String
  IngestionStateMachineArn:
    Type: String

Globals:
  Function:
    Timeout: 300
    Tracing: Active
    Runtime: python3.13
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON

Resources:
  IngestionDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600

  IngestionQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt IngestionDLQ.Arn
        maxReceiveCount: 5

  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWSAccountName}-${AWS::StackName}-ingestion-worker'
      Handler: app.lambda_handler
      Runtime: python3.13
      CodeUri: ./worker-lambda/
      Role: !Ref LambdaIAMRoleARN
      MemorySize: 512
      Timeout: 300
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupID1
          - !Ref LambdaSecurityGroupID2
        SubnetIds:
          - !Ref LambdaSubnet1ID
          - !Ref LambdaSubnet2ID
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref IngestionStateMachineArn
          QUEUE_URL: !Ref IngestionQueue
      Events:
        Queue:
          Type: SQS
          Properties:
            Queue: !GetAtt IngestionQueue.Arn
            BatchSize: 10

  WorkerSQSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWSAccountName}-${AWS::StackName}-worker-sqs'
      Roles:
        - !Select [1, !Split ['/', !Ref LambdaIAMRoleARN]]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt IngestionQueue.Arn

  StepFunctionInvokePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AWSAccountName}-${AWS::StackName}-sf-start'
      Roles:
        - !Select [1, !Split ['/', !Ref LambdaIAMRoleARN]]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: states:StartExecution
            Resource: !Ref IngestionStateMachineArn

Outputs:
  IngestionQueueUrl:
    Description: URL of the ingestion queue
    Value: !Ref IngestionQueue
