version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: services/entity-tokenization/Dockerfile
    environment:
      TOKEN_TABLE: token-table
      TOKEN_PREFIX: ent_
      TOKEN_SALT: ''
    ports:
      - "9000:8080"
