AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample serverless stack with eight Lambda functions.

Parameters:
  BUCKET_NAME:
    Type: String
    Description: S3 bucket storing all pipeline objects
  RAW_PREFIX:
    Type: String
    Default: raw/
  CLASSIFIED_PREFIX:
    Type: String
    Default: classified/
  OFFICE_PREFIX:
    Type: String
    Default: office/
  SPLIT_PREFIX:
    Type: String
    Default: split/
  PAGE_PREFIX:
    Type: String
    Default: pages/
  TEXT_PREFIX:
    Type: String
    Default: text/
  OCR_PREFIX:
    Type: String
    Default: ocr/
  COMBINE_PREFIX:
    Type: String
    Default: combine/
  OUTPUT_PREFIX:
    Type: String
    Default: output/
  TEXT_DOC_PREFIX:
    Type: String
    Default: text-docs/
  OCR_ENGINE:
    Type: String
    Default: easyocr
  TROCR_ENDPOINT:
    Type: String
    Default: ''
  DOCLING_ENDPOINT:
    Type: String
    Default: ''

Globals:
  Function:
    Runtime: python3.13
    Handler: handler.lambda_handler
    Timeout: 300
    MemorySize: 512
    Role: !GetAtt LambdaExecutionRole.Arn
    Environment:
      Variables:
        BUCKET_NAME: !Ref BUCKET_NAME
        RAW_PREFIX: !Ref RAW_PREFIX
        CLASSIFIED_PREFIX: !Ref CLASSIFIED_PREFIX
        OFFICE_PREFIX: !Ref OFFICE_PREFIX
        SPLIT_PREFIX: !Ref SPLIT_PREFIX
        PAGE_PREFIX: !Ref PAGE_PREFIX
        TEXT_PREFIX: !Ref TEXT_PREFIX
        OCR_PREFIX: !Ref OCR_PREFIX
        COMBINE_PREFIX: !Ref COMBINE_PREFIX
        OUTPUT_PREFIX: !Ref OUTPUT_PREFIX
        TEXT_DOC_PREFIX: !Ref TEXT_DOC_PREFIX
        OCR_ENGINE: !Ref OCR_ENGINE

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub arn:aws:s3:::${BUCKET_NAME}/*

  OCRLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ocr-layer
      Description: OCR layer with PyMuPDF and EasyOCR
      ContentUri: ../../common/layers/ocr_layer/
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  ClassifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./1-classifier/
      Events:
        RawUpload:
          Type: S3
          Properties:
            Bucket: !Ref BUCKET_NAME
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref RAW_PREFIX

  OfficeExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./2-office-extractor/
      Events:
        FromClassifier:
          Type: S3
          Properties:
            Bucket: !Ref BUCKET_NAME
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref CLASSIFIED_PREFIX

  PdfSplitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./3-pdf-split/
      Events:
        FromOffice:
          Type: S3
          Properties:
            Bucket: !Ref BUCKET_NAME
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref OFFICE_PREFIX

  PdfPageClassifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./4-pdf-page-classifier/
      Events:
        FromSplit:
          Type: S3
          Properties:
            Bucket: !Ref BUCKET_NAME
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref SPLIT_PREFIX

  PdfTextExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./5-pdf-text-extractor/
      Events:
        FromPageClassifier:
          Type: S3
          Properties:
            Bucket: !Ref BUCKET_NAME
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref PAGE_PREFIX

  PdfOcrExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./6-pdf-ocr-extractor/
      Layers:
        - !Ref OCRLayer
      Environment:
        Variables:
          OCR_ENGINE: !Ref OCR_ENGINE
          TROCR_ENDPOINT: !Ref TROCR_ENDPOINT
          DOCLING_ENDPOINT: !Ref DOCLING_ENDPOINT
      Events:
        FromTextExtractor:
          Type: S3
          Properties:
            Bucket: !Ref BUCKET_NAME
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref TEXT_PREFIX

  CombineFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./7-combine/
      Events:
        FromOcr:
          Type: S3
          Properties:
            Bucket: !Ref BUCKET_NAME
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref OCR_PREFIX

  OutputFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./8-output/
      Events:
        FromCombine:
          Type: S3
          Properties:
            Bucket: !Ref BUCKET_NAME
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Ref COMBINE_PREFIX

Outputs:
  ClassifierFunctionArn:
    Description: ARN of the classifier Lambda function
    Value: !GetAtt ClassifierFunction.Arn
  OfficeExtractorFunctionArn:
    Description: ARN of the office extractor Lambda function
    Value: !GetAtt OfficeExtractorFunction.Arn
  PdfSplitFunctionArn:
    Description: ARN of the PDF split Lambda function
    Value: !GetAtt PdfSplitFunction.Arn
  PdfPageClassifierFunctionArn:
    Description: ARN of the PDF page classifier Lambda function
    Value: !GetAtt PdfPageClassifierFunction.Arn
  PdfTextExtractorFunctionArn:
    Description: ARN of the PDF text extractor Lambda function
    Value: !GetAtt PdfTextExtractorFunction.Arn
  PdfOcrExtractorFunctionArn:
    Description: ARN of the PDF OCR extractor Lambda function
    Value: !GetAtt PdfOcrExtractorFunction.Arn
  CombineFunctionArn:
    Description: ARN of the combine Lambda function
    Value: !GetAtt CombineFunction.Arn
  OutputFunctionArn:
    Description: ARN of the output Lambda function
    Value: !GetAtt OutputFunction.Arn
  OCRLayerArn:
    Description: ARN of the OCR shared layer
    Value: !Ref OCRLayer
  BucketName:
    Description: Input and output S3 bucket
    Value: !Ref BUCKET_NAME
  TextDocPrefix:
    Description: Prefix for combined text documents
    Value: !Ref TEXT_DOC_PREFIX

