version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: services/rag-retrieval/Dockerfile
    environment:
      VECTOR_SEARCH_FUNCTION: vector-search
    ports:
      - "9009:8080"
