AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Generate ACORD 103 XML from extracted data.

Parameters:
  AWSAccountName:
    Type: String
  LambdaSubnet1ID:
    Type: String
  LambdaSubnet2ID:
    Type: String
  LambdaSecurityGroupID1:
    Type: String
  LambdaSecurityGroupID2:
    Type: String
  LambdaIAMRoleARN:
    Type: String
  CaseImportEndpoint:
    Type: String
    Description: API endpoint for CaseImport service

Globals:
  Function:
    Timeout: 10
    Runtime: python3.13
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  AcordGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWSAccountName}-${AWS::StackName}-acord-generator'
      Handler: generate_xml_lambda.lambda_handler
      CodeUri: ./src/
      Runtime: python3.13
      Role: !Ref LambdaIAMRoleARN
      MemorySize: 512
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupID1
          - !Ref LambdaSecurityGroupID2
        SubnetIds:
          - !Ref LambdaSubnet1ID
          - !Ref LambdaSubnet2ID
      Environment:
        Variables:
          CASEIMPORT_ENDPOINT: !Ref CaseImportEndpoint

Outputs:
  AcordGeneratorFunctionArn:
    Description: ARN of the ACORD generator Lambda
    Value: !GetAtt AcordGeneratorFunction.Arn
