version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: services/email-classifier-service/Dockerfile
    environment:
      AWS_ACCOUNT_NAME: dev
      RULES_TABLE: emailRules
    ports:
      - "9010:8080"
