version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: services/rag-stack/Dockerfile
    environment:
      CHUNK_SIZE: '1000'
      STATE_MACHINE_ARN: arn:aws:states:region:acct:stateMachine:ingest
      QUEUE_URL: https://sqs.region.amazonaws.com/123/queue
      VECTOR_SEARCH_FUNCTION: vector-search
    ports:
      - "9014:8080"
