AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda to detect sensitive information such as PII or PHI.

Parameters:
  NerLibrary:
    Type: String
    Default: 'spacy'
  SpacyModel:
    Type: String
    Default: 'en_core_web_sm'
  HFModel:
    Type: String
    Default: 'dslim/bert-base-NER'
  MedicalModel:
    Type: String
    Default: 'emilyalsentzer/Bio_ClinicalBERT'
  LegalModel:
    Type: String
    Default: 'dslim/bert-base-NER'
  RegexPatterns:
    Type: String
    Default: '{"SSN": "\\b\\d{3}-\\d{2}-\\d{4}\\b", "CREDIT_CARD": "\\b(?:\\d[ -]*?){13,16}\\b"}'
  LegalRegexPatterns:
    Type: String
    Default: '{"CASE_NUMBER": "\\b\\d{2}-\\d{5}\\b"}'

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.13
    Timeout: 60
    MemorySize: 512

Resources:
  DetectPiiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./detect-pii-lambda/
      Environment:
        Variables:
          NER_LIBRARY: !Ref NerLibrary
          SPACY_MODEL: !Ref SpacyModel
          HF_MODEL: !Ref HFModel
          MEDICAL_MODEL: !Ref MedicalModel
          LEGAL_MODEL: !Ref LegalModel
          REGEX_PATTERNS: !Ref RegexPatterns
          LEGAL_REGEX_PATTERNS: !Ref LegalRegexPatterns
      Events:
        Api:
          Type: Api
          Properties:
            Path: /detect-pii
            Method: post

Outputs:
  DetectPiiFunctionArn:
    Description: ARN of the PII detection Lambda
    Value: !GetAtt DetectPiiFunction.Arn
