version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: services/prompt-engine/Dockerfile
    environment:
      PROMPT_LIBRARY_TABLE: prompts
      ROUTER_ENDPOINT: http://router
    ports:
      - "9007:8080"
