version: '3.8'
services:
  app:
    build:
      context: ../..
      dockerfile: services/llm-router/Dockerfile
    environment:
      LLM_INVOCATION_FUNCTION: invoke-llm
    ports:
      - "9006:8080"
