AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambdas for RAG retrieval.

Parameters:
  SummaryEndpoint:
    Type: String
    Default: ''
  ContentEndpoint:
    Type: String
    Default: ''
  EntitiesEndpoint:
    Type: String
    Default: ''
  RouteLlmEndpoint:
    Type: String
    Default: ''
  VectorSearchFunctionArn:
    Type: String
  RerankFunctionArn:
    Type: String
    Default: ''
  VectorSearchCandidates:
    Type: String
    Default: '5'

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.13
    Timeout: 60
    MemorySize: 512

Resources:

  SummarizeWithContextFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./summarize-with-context-lambda/
      Environment:
        Variables:
          VECTOR_SEARCH_FUNCTION: !Ref VectorSearchFunctionArn
          RERANK_FUNCTION: !Ref RerankFunctionArn
          VECTOR_SEARCH_CANDIDATES: !Ref VectorSearchCandidates
          SUMMARY_ENDPOINT: !Ref SummaryEndpoint
          ROUTELLM_ENDPOINT: !Ref RouteLlmEndpoint
      Events:
        Api:
          Type: Api
          Properties:
            Path: /summarize
            Method: post

  ContentExtractionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./extract-content-lambda/
      Environment:
        Variables:
          VECTOR_SEARCH_FUNCTION: !Ref VectorSearchFunctionArn
          CONTENT_ENDPOINT: !Ref ContentEndpoint
      Events:
        Api:
          Type: Api
          Properties:
            Path: /extract-content
            Method: post

  EntityExtractionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./extract-entities-lambda/
      Environment:
        Variables:
          VECTOR_SEARCH_FUNCTION: !Ref VectorSearchFunctionArn
          ENTITIES_ENDPOINT: !Ref EntitiesEndpoint
      Events:
        Api:
          Type: Api
          Properties:
            Path: /extract-entities
            Method: post

  RerankFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./rerank-lambda/
      Environment:
        Variables:
          TOP_K: !Ref VectorSearchCandidates
          CROSS_ENCODER_MODEL: ''

Outputs:
  RerankFunctionArn:
    Description: ARN of the re-rank Lambda
    Value: !GetAtt RerankFunction.Arn
  SummarizeWithContextFunctionArn:
    Description: ARN of the summarize-with-context Lambda
    Value: !GetAtt SummarizeWithContextFunction.Arn

